# prepare operation:
#   mkdir esdatadir
#   chmod g+rwx esdatadir
#   chgrp 1000 esdatadir

version: '3'
services:
  elasticsearch:
    image: linzhs/elasticsearch:7.3.1
    container_name: elasticsearch-dev
    environment:
      - node.name=elasticsearch-dev01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - xpack.security.enabled=true
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/opt/elasticsearch/data:/usr/share/elasticsearch/data"
      - "/opt/elasticsearch/config:/usr/share/elasticsearch/config"
    ports:
      - "18200:9200"
    networks:
      - elknet
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana-dev
    environment:
      - SERVER_NAME=kibana-dev
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLE=true
    ports:
      - "15601:5601"
    networks:
      - elknet
    depends_on:
      - elasticsearch
  
  cerebro:
    image: cerebro:0.8.4
    container_name: cerebro-dev
    ports:
      - "19000:9000"
    networks:
      - elknet
    depends_on:
      - elasticsearch
networks: 
  elknet: